plugins {
    id 'com.android.application'
}

android {
    namespace 'com.fadeds.livetv'
    compileSdk 34

    defaultConfig {
        applicationId "com.fadeds.livetv"
        minSdk 23
        targetSdk 33
        versionCode = project.findProperty("VERSION_CODE")?.toString()?.toInteger() ?: 9
        versionName = project.findProperty("VERSION_NAME")?.toString() ?: "0.0.9"
    }

    signingConfigs {
        release {
            storeFile file(System.getenv("CCTV_KEYSTORE") ?: "release.keystore")
            storePassword System.getenv("CCTV_KSPASS") ?: "cctv123456"
            keyAlias System.getenv("CCTV_KEYALIAS") ?: "cctv"
            keyPassword System.getenv("CCTV_KEYPASS") ?: "cctv123456"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
}